name: 'Create Translation Pull Requests'
description: 'Create pull requests for translation forks'
inputs:
  GH_TOKEN:
    description: 'The secret GitHub token, use to create the pull requests'
    required: true
  FORKS:
    description: 'An array of forks ("owner/repo"), in line-separated format (because GitHub doesn\'t support array input yet'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'