name: 'Create Translation Pull Requests'
description: 'Create pull requests for translation forks'
inputs:
  GH_TOKEN:
    description: 'The secret GitHub token, use to create the pull requests'
    required: true
  FORKS:
    description: 'Line-separated forks (in "owner/repo" format)'
    required: true
outputs:
  prs:
    description: 'URLs of created pull requests'
runs:
  using: 'node12'
  main: 'dist/index.js'